DESKTOP VERSION OF PORTFOLIO-WEBSITE
citec-47/Desktop-version pull request #1
Opened 2023-02-23 06:59 UTC by citec-47

##General requirements🧾
-Make sure that there are [no linter errors] (https://github.com/microverseinc/linters-config).
-Make sure that you used correct ([GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git github/articles/github_flow.md).
-Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
#HTML/CSS requirements
-Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
#Project requirements🌳
-IMPORTANT NOTE: For each Microverse project, you need to create a separate pull request. [Read how to work with multiple pull requests in your one repository in the most efficient way](https://github.com/microverseinc/curriculum-transversal--skills/blob/main/git-github/articles/multiple_pull_requests.md).

-You need to make sure that your dekstop version looks like the one in the Figma design template that you chose. We include a screenshot of Template 1 below for reference, but you should use the template that you chose.

-IMPORTANT NOTE some Figma design templates include two input fields (for first name and last name) in the desktop version and one input field (for full name) in the mobile version (look for those cases in Contact me or Get in touch sections). Please ignore this part of the design template and use only one input for the full name for all versions.

#Desktop

-Use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: >=768px).

-In order to lay out the elements on the page you should use Grid and Flexbox.

-You don't need to implement any functionality that requires JavaScript.

2023-02-23 07:20 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @citec-47 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a project, that lacks a descriptive README file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-23 07:37 UTC, citec-47 commented
#README FILE
-adjustment of my readme file

2023-02-23 07:41 UTC, amejid reviewed
Hi @citec-47, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, where the PR description is directly copied from the project requirements. Kindly put a summary of the introduced changes inside your PR description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-23 07:59 UTC, citec-47 commented
#adjustment of the PR form

2023-02-23 08:51 UTC, levy002 requested changes
## Hello @citec-47   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to fix the styling on the `Get my resume` button on the mobile version because now it now looking like the one on the Figma design.

   - ### YOUR DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/220859729-593d6867-02a9-4b23-a2cf-a9ed4f34ca1e.png)

   - ### FIGMA DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/220859887-1f95be1c-8b2b-4aaf-b2d4-2401aa04940b.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 08:51 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure to align the content of this container correctly in order to meet the Figma design as much as possible. You can use CSS flexbox to achieve that.
- [ ] Kindly make sure to fix this headline section on the mobile version.

   - ### YOUR DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/220856608-62640235-7e0a-482b-b1b4-d891d608ce5c.png)

   ![image](https://user-images.githubusercontent.com/87197412/220859128-5d2b3e1f-195f-4e03-a6a5-22fa11d55ff6.png)

   - ### FIGMA DESIGN
   
   ![image](https://user-images.githubusercontent.com/87197412/220856734-4463d5ed-a17c-40aa-b1f3-1a7088e9eba7.png)

   ![image](https://user-images.githubusercontent.com/87197412/220859234-49da85a9-30f0-4810-82c3-cb6c0270561c.png)

2023-02-23 08:51 UTC, levy002 commented on style.css
> +  }
- [ ] Kindly make sure to add the `border-radius` on the `submit` button in order to meet the Figma design as much as possible.

  - ### YOUR DESIGN
  
     ![image](https://user-images.githubusercontent.com/87197412/220857139-6f631a1b-c486-42fb-a1c5-e0460eed66da.png)

  - ### FIGMA DESIGN
  
   ![image](https://user-images.githubusercontent.com/87197412/220857208-7ae7ee42-447e-4b9e-b01f-56875f63d82e.png)

2023-02-24 14:03 UTC, citec-47 commented
#Changes
[]styling on the Get my resume button
[]fixing of the header section on of the mobile version
[]

2023-02-24 14:28 UTC, frank1738 approved these changes
Hi @citec-47  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good Documentation 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 16:27 UTC, merged